[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && cd server && npm install"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/healthz"
restartPolicyType = "ON_FAILURE"
